const ADD_PRODUCT = "ADD_PRODUCT";
const SELECT_PRODUCT = "SELECT_PRODUCT";
const FETCH_PRODUCT = "FETCH_PRODUCT";
const REQUEST_PRODUCT = "REQUEST_PRODUCT";
const ERROR_PRODUCT = "ERROR_PRODUCT";
const DELETE_PRODUCT = "DELETE_PRODUCT";
const UPDATE_PRODUCT = "UPDATE_PRODUCT";
const SEARCH_PRODUCT = "SEARCH_PRODUCT";

const SELECT_PRODUCT_DETAIL = "SELECT_PRODUCT_DETAIL";
const FETCH_PRODUCT_DETAIL = "FETCH_PRODUCT_DETAIL";
const REQUEST_PRODUCT_DETAIL = "REQUEST_PRODUCT_DETAIL";
const ERROR_PRODUCT_DETAIL = "ERROR_PRODUCT_DETAIL";

const REAL_TIME_SEARCH = "REAL_TIME_SEARCH";
const REGULAR_SEARCH = "REGULAR_SEARCH";
const CLEAR_ICON_ON = "CLEAR_ICON_ON";
const CLEAR_ICON_OFF = "CLEAR_ICON_OFF";

const ADD_TO_CART = "ADD_TO_CART";
const DELETE_CART_ITEM = "DELETE_CART_ITEM";
const CHANGE_CART_ITEM_QUANTITY = "CHANGE_CART_ITEM_QUANTITY";
const FETCH_COOKIE_ITEMS_TO_CART = "FETCH_COOKIE_ITEMS_TO_CART";
const RESET_COOKIE_AND_CART = "RESET_COOKIE_AND_CART";

const ADD_ORDER = "ADD_ORDER";
const REQUEST_ORDER = "REQUEST_ORDER";
const FETCH_ORDER = "FETCH_ORDER";

const ADD_PAYMENT = "ADD_PAYMENT";

const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";
const USER_SIGNOUT = "USER_SIGNOUT";

const REQUEST_RECEIPT = "REQUEST_RECEIPT";
const FETCH_RECEIPT = "FETCH_RECEIPT";

exports.ADD_PRODUCT = ADD_PRODUCT;
exports.SELECT_PRODUCT = SELECT_PRODUCT;
exports.FETCH_PRODUCT = FETCH_PRODUCT;
exports.REQUEST_PRODUCT = REQUEST_PRODUCT;
exports.ERROR_PRODUCT = ERROR_PRODUCT;
exports.DELETE_PRODUCT = DELETE_PRODUCT;
exports.UPDATE_PRODUCT = UPDATE_PRODUCT;
exports.SEARCH_PRODUCT = SEARCH_PRODUCT;

exports.SELECT_PRODUCT_DETAIL = SELECT_PRODUCT_DETAIL;
exports.FETCH_PRODUCT_DETAIL = FETCH_PRODUCT_DETAIL;
exports.REQUEST_PRODUCT_DETAIL = REQUEST_PRODUCT_DETAIL;
exports.ERROR_PRODUCT_DETAIL = ERROR_PRODUCT_DETAIL;

exports.REAL_TIME_SEARCH = REAL_TIME_SEARCH;
exports.REGULAR_SEARCH = REGULAR_SEARCH;
exports.CLEAR_ICON_ON = CLEAR_ICON_ON;
exports.CLEAR_ICON_OFF = CLEAR_ICON_OFF;

exports.ADD_TO_CART = ADD_TO_CART;
exports.DELETE_CART_ITEM = DELETE_CART_ITEM;
exports.CHANGE_CART_ITEM_QUANTITY = CHANGE_CART_ITEM_QUANTITY;
exports.FETCH_COOKIE_ITEMS_TO_CART = FETCH_COOKIE_ITEMS_TO_CART;
exports.RESET_COOKIE_AND_CART = RESET_COOKIE_AND_CART;

exports.ADD_ORDER = ADD_ORDER;
exports.REQUEST_ORDER = REQUEST_ORDER;
exports.FETCH_ORDER = FETCH_ORDER;

exports.ADD_PAYMENT = ADD_PAYMENT;


exports.USER_SIGNIN_REQUEST = USER_SIGNIN_REQUEST;
exports.USER_SIGNIN_SUCCESS = USER_SIGNIN_SUCCESS;
exports.USER_SIGNIN_FAIL = USER_SIGNIN_FAIL;
exports.USER_SIGNOUT = USER_SIGNOUT;

exports.REQUEST_RECEIPT = REQUEST_RECEIPT;
exports.FETCH_RECEIPT = FETCH_RECEIPT;